### ISSUE TITLE
Kudos, great project!

### ISSUE THREAD

**Issue by Malensky** [jacobroufa/midi_c4_preset#2]
Hi there,

This is just to say congrats, seems like a great project! I own a C4 and I need that controller desperately. I purchased the Trinket M0, however I find the 7-segment display to be quite bulky for my purposes. I saw a LCD in the pull requests, what kind are you planning on implementing? When do you think the new functionalities will be ready?

Sorry to be so impatient, thanks for your hard work!
Warmly,
Malen

**Comment by jacobroufa** [comment]
Hey Malen!

Thanks so much for the feedback! My LCD is a 20x2 i2c display, which is quite a bit larger than the 7-segment. I have a version implemented which functions acceptably but I have had some issues getting the EEPROM to work to save settings. This is my first serious attempt at C++, outside of some hello worlds I don't really have any experience with it, so there's been a bit of a learning curve. I work primarily with TypeScript and C# at work though so I'm not flying totally blind.

Here are a few pictures of the new controller and the first version
https://imgur.com/a/L1aQLOi

As you can see there are 6 buttons compared to the 2 on the original, the larger LCD, an expression pedal output, and an ItsyBitsy M0 instead of the Trinket.

This has so far just been a hobby project, but I'm happy to think a bit more about throwing together a new release, while I sort out the EEPROM. I got stuck on that in November, then had too much else to think about.

I still have a 2-button version though as I originally built it, which I intend to update slightly. You can see the packaging in the photos above if that's your concern. Originally I had just some double sided tape to mount the 7-segment but I ended up printing a short spacer to place it flush against the case.

Regards,
Jacob

**Comment by Malensky** [comment]
Thank you once again, wonderful! Hope you get it to work soon! For now I will build the first version and wait for the second.
Cheers,
Malen

**Comment by Malensky** [comment]
Hello again, do you think it will work if I put a 1.3 OLED display instead of the TM1637 ? And find the corresponding library...
